---

- name: install packages
  apt: name={{ item }}
       state=latest
       default_release=stretch-backports
       install_recommends=no
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - nfs-common

- name: limit portmap access
  lineinfile: dest={{item.dest}} regexp='rpcbind' line={{item.line}}
  with_items: 
    - {dest: /etc/hosts.deny, line: 'rpcbind: ALL'}
    - {dest: /etc/hosts.allow, line: 'rpcbind: 127.0.0.1 10.0.0.0/8'}
  tags:
    - security

- name: setup open files soft limit
  lineinfile: dest=/etc/security/limits.conf regexp='soft.*nofile' line='* soft nofile 65535'

- name: setup open files hard limit
  lineinfile: dest=/etc/security/limits.conf regexp='hard.*nofile' line='* hard nofile 65535'

- name: configure grub cgroups
  lineinfile: dest=/etc/default/grub
              regexp=^GRUB_CMDLINE_LINUX=
              line='GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 cgroup_enable=memory swapaccount=1 transparent_hugepage=never net.ifnames=0 biosdevname=0"'
  notify:
    - update grub

#- name: configure grub default
#  lineinfile: dest=/etc/default/grub regexp='^GRUB_DEFAULT=' line='GRUB_DEFAULT=1'
#  notify:
#    - update grub

- name: enable interfaces.d directory
  lineinfile: dest=/etc/network/interfaces regexp='^source-directory' line='source-directory interfaces.d'
  tags:
    - eth1

- name: install interface 
  template: src=eth1.j2 dest=/etc/network/interfaces.d/eth1 mode=644
  register: update_eth1
  tags:
    - eth1

- name: enable eth1
  command: /sbin/ifup --force eth1
  when: update_eth1.changed
  tags:
    - eth1

#- name: install acme script
#  template: src=register-acme-cert.sh.j2 dest=/usr/bin/register-acme-cert mode=0755


- name: sysctl tuning (ovh)
  sysctl: name={{item.key}} value={{item.val}} state=present
  with_items:
    - { key: net.ipv6.conf.eth0.autoconf, val: 0 }
    - { key: net.ipv6.conf.eth0.accept_ra, val: 0 }
