---

- name: set cni vlan config file
  template: src=cni.json.j2 dest=/etc/cni/net.d/10-vlan.conf mode=0644
  tags:
    - cni

- name: install cni plugins
  get_url: url=https://github.com/projectcalico/calico-cni/releases/download/v1.5.5/{{item}} dest=/opt/cni/bin/{{item}} mode=0755
  with_items:
    - calico
    - calico-ipam
  tags:
    - cni

- name: install calicoctl wrapper
  template: src=calicoctl.j2 dest=/usr/bin/calicoctl mode=0755
  tags:
    - cni