#!/bin/sh
CACHE_DIR=/mnt/cache/store/docker  #docker_store_dir

ls $CACHE_DIR/layers | sort -u > /tmp/_layers
ls -al /tmp/* | grep $CACHE_DIR | awk -F'/' '{print $7}' | sort -u > /tmp/_used
for d in $(comm -3 /tmp/_layers /tmp/_used)
do
  rm -rf $CACHE_DIR/layers/$d
done
rm /tmp/_layers /tmp/_used