#!/bin/bash

usage () {
    echo "$0 pid [command]"
    exit 1
}

[ -n "$1" ] || usage
NSPID=$1

NSCMD="sh"
[ -z "$2" ] || NSCMD=$2

MEPID=$(ps -eo pid,ppid | grep "${NSPID}$" | awk '{print $1}' | head -n 1)

OLD=$IFS
IFS=$'\n'
ENV=( $(tr '\n' ' ' < /proc/$MEPID/environ | sed -e 's/\x0/\n/g') )
IFS=$OLD

exec nsenter -t $NSPID -m -n -p -i -r -w -u env -i - "${ENV[@]}" $NSCMD
