#!/bin/bash

usage () {
    echo "$0 ip [command]"
    exit 1
}

nopid () {
    echo "cannot find pid for ip ${NSIP}"
    exit 1
}

[ -n "$1" ] || usage
NSIP=$1

NSCMD="sh"
[ -z "$2" ] || NSCMD=$2

. /etc/default/mesos

NSPID=$(curl -s ${IP}:5051/containers | jq ".[] | select(.status .network_infos[]? | select(.ip_addresses[0].ip_address == \"${1}\")) |  .status .executor_pid")

[ -n "$NSPID" ] || nopid

MEPID=$(ps -eo pid,ppid | grep "${NSPID}$" | awk '{print $1}' | head -n 1)
CHILDPID=$(ps -eo pid,ppid | grep "${MEPID}$" | awk '{print $1}' | head -n 1)

OLD=$IFS
IFS=$'\n'
ENV=( $(tr '\n' ' ' < /proc/$MEPID/environ | sed -e 's/\x0/\n/g') )
IFS=$OLD

exec nsenter -t $CHILDPID -m -n -p -i -r -w -u env -i - "${ENV[@]}" $NSCMD
