---
- name: install haproxy
  apt: name=haproxy state=latest default_release=stretch-backports install_recommends=no update_cache=yes cache_valid_time=3600

- name: create haproxy service dir
  file: state=directory path=/etc/sv/haproxy

- name: update haproxy run file
  copy: src=run.sh dest=/etc/sv/haproxy/run mode=0755
  notify:
    - restart haproxy
  tags:
    - haproxy

- name: update consul template 
  template: src=consul-template.tmpl.j2 dest=/etc/consul-template/templates.d/haproxy.tmpl mode=0644
  notify:
    - reload consul-template
  tags:
    - haproxy
    
- name: update consul-template config 
  copy: src=consul-template.hcl dest=/etc/consul-template/conf.d/haproxy.hcl mode=0644
  notify:
    - reload consul-template
  tags:
    - haproxy

- name: configure haproxy service
  runit: name=haproxy enabled=true state=started service_dir=/etc/service
  tags:
    - haproxy

- name: disable sysv haproxy service
  service: name=haproxy state=stopped enabled=no
  tags:
    - haproxy
