---

- name: install felix
  unarchive: src=https://github.com/projectcalico/felix/releases/download/2.0.0/calico-felix-2.0.0.tgz
    dest=/opt
    copy=no
  tags:
    - calico

- name: remove libtinfo.so.5 from felix (ncurses bug)
  file: path=/opt/calico-felix/libtinfo.so.5 state=absent
  tags:
    - calico

- name: link calico-iptables-plugin in the path
  file: src=/opt/calico-felix/calico-iptables-plugin dest=/usr/bin/calico-iptables-plugin state=link
  tags:
    - calico

- name: install bird
  get_url: url=https://github.com/projectcalico/calico-bird/releases/download/v0.2.0-rc1/bird
    dest=/usr/bin/bird
    mode=0755
    checksum=md5:aa65a3b09d5a6864a3832f9d94a77fb7
  tags:
    - calico

- name: install bird6
  get_url: url=https://github.com/projectcalico/calico-bird/releases/download/v0.2.0-rc1/bird6
    dest=/usr/bin/bird6
    mode=0755
    checksum=md5:1858cc78b7d77a66b364cf065cdcf8b6
  tags:
    - calico

- name: install birdcl
  get_url: url=https://github.com/projectcalico/calico-bird/releases/download/v0.2.0-rc1/birdcl
    dest=/usr/bin/birdcl
    mode=0755
    checksum=md5:9233f40f4d9b99ea051441c38685fb19
  tags:
    - calico

- name: install calico-bgp-daemon
  get_url: url=https://github.com/projectcalico/calico-bgp-daemon/releases/download/v0.1.1-rc3/calico-bgp-daemon
    dest=/usr/bin/calico-bgp-daemon
    mode=0755    
    checksum=md5:fa627e6c4fc03267b0c228b163b3fef2
  tags:
    - calico

- name: install gobgp
  get_url: url=https://github.com/projectcalico/calico-bgp-daemon/releases/download/v0.1.1-rc3/gobgp
    dest=/usr/bin/gobgp
    mode=0755
    checksum=md5:56482919c50fea87de294f278b42178f
  tags:
    - calico

- name: install confd
  get_url: url=https://github.com/projectcalico/confd/releases/download/v0.10.0-scale/confd.static
    dest=/usr/bin/confd.static
    mode=0755
    checksum=md5:6d5a47c3e064e69047e0c05a0b1029e5
  tags:
    - calico

- name: install calicoctl binary
  get_url: url=https://github.com/projectcalico/calico-containers/releases/download/v1.0.0/calicoctl
    dest=/usr/bin/calicoctl.bin
    mode=0755
    checksum=md5:becfd242015d66b7b508f2626273ff3f
  tags:
    - calico

- name: install calico-startup
  copy: src=startup dest=/usr/bin/calico-startup mode=0755
  tags:
    - calico

- name: install allocate-ipip-addr
  copy: src=allocate-ipip-addr dest=/usr/bin/allocate-ipip-addr mode=0755
  tags:
    - calico

- name: install calico dependencies
  apt: name={{ item }}
       state=latest
       default_release=jessie-backports
       install_recommends=no
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - ipset
    - conntrack
  tags:
    - calico

- name: create calico directories
  file: state=directory path={{ item }}
  with_items:
    - /etc/calico
    - /etc/sv/felix
    - /etc/sv/confd
    - /etc/sv/bird
    - /etc/sv/bird6
    - /var/run/calico
  tags:
    - calico

- name: install calico config and templates
  copy: src={{item}} dest=/etc/calico/
  with_items:
    - felix.cfg
    - confd
  tags:
    - calico

- name: update run files
  template: src={{item}}.sh.j2 dest=/etc/sv/{{item}}/run mode=0755
  with_items:
    - felix
    - confd
    - bird
    - bird6
  notify:
    - restart {{item}}
  tags:
    - calico

- name: configure calico services
  runit: name={{item}} enabled=true state=up timeout=9 user='root' auto=no has_log=no
  with_items:
    - felix
    - confd
    - bird
    - bird6
  tags:
    - calico
